In [1231]:
sample_size = 10

In [1232]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import adjusted_rand_score, normalized_mutual_info_score
from sklearn.cluster import KMeans
from sklearn.neighbors import KNeighborsRegressor
import warnings
warnings.filterwarnings("ignore")

In [1233]:
gene_df = pd.read_csv('data/gene_spec.csv')
morph_df = pd.read_csv('data/morph.csv')

In [1234]:
morph_df = morph_df.drop(['idx', 'Date', 'classification', 'uncertainty','Latitude', 'Longitude', 'Altitude.ft', 'Multi.Single.stem', 'General.location.Habitat', 'site', 'Putative_spp'], axis=1)
morph_df = morph_df.dropna()
morph_df = morph_df.replace(0, 1e-10)

data = morph_df.drop(['TreeNo'], axis=1)

scaler = StandardScaler()
data = scaler.fit_transform(data)
data = data[:, [0, 11, 7, 12, 16]]
kmeans = KMeans(n_clusters=3, random_state=0)
cluster_labels = kmeans.fit_predict(data)

morph_df['morph_cluster'] = cluster_labels
morph_df

TreeNo  height    log.BL    log.PL    log.BW  log.TLIW   log.TLL  \
0    M-QR2     1.5  2.414960  0.451813  2.215436  0.971517  1.492824   
1    M-QA2     2.5  2.429840  0.813196  2.272111  1.241901  0.652962   
2    M-QA3     2.5  2.723339  1.339852  2.577227  1.887415  1.372193   
3    M-QA4     3.0  2.458778  0.678297  2.181339  1.478614  1.019372   
4    M-QA5     2.2  2.523282  0.675473  2.434660  1.722535  1.445529   
..     ...     ...       ...       ...       ...       ...       ...   
522   QS56    18.0  2.578621  1.234275  2.377050  1.193146  1.300033   
523   QS57    20.0  2.540898  1.358887  2.535179  1.073146  1.323958   
524   QS58    18.0  2.665272  1.218970  2.382819  1.417496  1.382116   
525   QS59    20.0  2.767293  1.425606  2.456724  1.571632  1.016609   
526   QS60    20.0  2.637481  1.340367  2.507497  1.420522  1.260841   

     log.TLDW   log.TEL   log.BLL   log.LLL   log.BSR   log.LSR  log.LLDW  \
0    1.236128  0.749326 -0.721076  1.248005  0.273287  1.937917  0.826713   
1    0.902493 -0.230920 -0.080406  0.940427  1.302997  2.247890  0.960641   
2    1.964269  0.576864 -0.086845  1.561296  1.107255  2.528339  1.453892   
3    1.268740  0.178144 -0.595116  0.928578  1.020238  2.269391  0.709607   
4    1.821472  0.509458  0.058145  1.409343  0.821479  2.189451  1.042951   
..        ...       ...       ...       ...       ...       ...       ...   
522  1.163951  0.464525  0.523280  1.170522  0.877163  2.280284  0.901729   
523  1.316130  0.350045  1.176558  1.463108  1.534398  2.223215  1.116863   
524  1.034352  0.231330  0.160398  1.360513  1.238391  2.360588  1.010989   
525  1.305160  0.228421  0.232765  1.156577  1.540165  2.601042  0.675069   
526  1.191419  0.179134  0.586648  1.329167  1.319265  2.369849  1.234624   

     log.LLIW  log.MidVeinD  log.BL_PL         Tufts  Lobe.number  \
0    1.051718      1.399480   2.546353  3.333333e-01     7.333333   
1    1.349103      1.684123   2.610964  6.666667e-01     7.000000   
2    1.807344      2.135655   2.947045  6.666667e-01     6.000000   
3    1.198653      1.748606   2.614548  1.000000e-10     8.333333   
4    1.410322      1.838945   2.669615  1.000000e-10     7.000000   
..        ...           ...        ...           ...          ...   
522  1.181146      1.749408   2.810296  2.000000e+00     8.666667   
523  1.302592      1.886950   2.808374  2.000000e+00     6.333333   
524  1.475226      1.886052   2.876699  2.000000e+00     7.000000   
525  1.311422      2.033878   2.999519  2.000000e+00     8.333333   
526  1.394891      1.944010   2.879109  2.000000e+00     7.666667   

     morph_cluster  
0                2  
1                2  
2                1  
3                2  
4                2  
..             ...  
522              0  
523              0  
524              0  
525              0  
526              0  

[494 rows x 20 columns]

In [1235]:
gene_df = gene_df[gene_df['spec'] != 'QB']
gene_df = gene_df.drop(['DNA_ID', 'spec'], axis=1)
data = gene_df.drop(['TreeNo'], axis=1)

scaler = StandardScaler()
data = scaler.fit_transform(data)
data = data[:, [1,2,0]]
kmeans = KMeans(n_clusters=3, random_state=0)
cluster_labels = kmeans.fit_predict(data)

gene_df['gene_cluster'] = cluster_labels
gene_df

PC1       PC2        PC3        PC4       PC5        PC6  \
0    21.708180 -1.917705  -1.904397   8.736799  0.215774   0.896592   
1    -5.810405 -0.052144  -9.538036  -2.079761 -3.775415   4.764205   
2    -8.408125 -2.288342   4.408345   1.755349 -0.421010  -0.327213   
3    11.720923 -1.770264   5.153834 -12.588452 -0.264384   1.568802   
4    -7.876694  0.132502 -12.803103  -0.833360 -7.874460 -23.156548   
..         ...       ...        ...        ...       ...        ...   
184  10.118824 -2.320689   6.742863 -14.984463 -0.767871   0.126735   
186 -11.141404 -1.784133  -4.296505  -0.003517 -3.353965   0.557499   
187  -5.711894  0.196501  -8.914460  -0.280047 -4.818608 -12.165693   
188  -9.590512  0.250831 -11.382537  -1.879106 -4.879972   5.505392   
189  -9.177109 -0.571629 -10.540330  -1.571035 -4.231814   5.444797   

           TreeNo  gene_cluster  
0          QR-PO2             2  
1           QA-S7             0  
2          SH-QS2             1  
3          SH-QR9             2  
4      Arnold-QA4             0  
..            ...           ...  
184        QS-L10             2  
186  QAC-G-0004-A             0  
187        QA-Pr1             0  
188        QA-PO6             0  
189       QA-PO15             0  

[179 rows x 8 columns]

In [1236]:
joined_df= morph_df.merge(gene_df, on='TreeNo')

# sample a random batch of rows
sample = joined_df.sample(sample_size)

# build an association matrix
association_matrix = np.zeros((3,3))
for i in range(3):
    for j in range(3):
        association_matrix[i,j] = np.sum((sample['morph_cluster'] == i) & (sample['gene_cluster'] == j))
print(association_matrix)

# Initialize decision array
decision = np.zeros(3, dtype=int)

# Create a copy of the association matrix to manipulate
temp_matrix = association_matrix.copy()

# Fill the decision array
for _ in range(3):
    max_index = np.argmax(temp_matrix)
    max_location = np.unravel_index(max_index, temp_matrix.shape)
    decision[max_location[0]] = max_location[1]
    temp_matrix[max_location[0], :] = -np.inf
    temp_matrix[:, max_location[1]] = -np.inf

print("Final decision array:")
print(decision)


[[0. 7. 0.]
 [0. 0. 2.]
 [0. 1. 0.]]
Final decision array:
[1 2 0]


In [1238]:
morph_df["morph_predicted_gene_cluster"] = morph_df.apply(lambda x: decision[x['morph_cluster']], axis=1)

average_gene = gene_df.groupby('gene_cluster').agg({'PC1': 'mean', 'PC2': 'mean', 'PC3': 'mean'}).reset_index()
average_gene['gene_centroids'] = average_gene[['PC1', 'PC2', 'PC3']].values.tolist()
average_gene = average_gene[['gene_cluster', 'gene_centroids']]

gene_df['gene_coordinates'] = gene_df[['PC1', 'PC2', 'PC3']].values.tolist()
gene_df = gene_df[['TreeNo', 'gene_coordinates']]
joined_df = morph_df.merge(gene_df, on='TreeNo').drop(['morph_cluster'], axis=1)

joined_df = joined_df.rename(columns={'morph_predicted_gene_cluster': 'gene_cluster'})
final_df = joined_df.merge(average_gene, on='gene_cluster')
final_df

TreeNo  height    log.BL    log.PL    log.BW  log.TLIW   log.TLL  \
0    QA-M11     3.0  2.339599  0.605942  2.308428  1.268776  1.328666   
1     QA-M5     4.5  2.417411  0.870383  2.359674  1.301971  1.361417   
2     QR-M1     3.0  2.845603  0.896078  2.726395  1.713517  1.861485   
3    QR-M14     2.5  2.585462  0.448939  2.376387  1.285094  1.401319   
4    QR-M15     4.0  2.533963  0.627553  2.506031  1.423807  1.241048   
..      ...     ...       ...       ...       ...       ...       ...   
110   QS-K3     7.0  2.459095  0.842046  2.602232  1.699206  1.527116   
111   QS-K6    15.0  2.810444  1.402410  2.705563  1.437666  1.120942   
112   QS-K7    17.0  2.765893  1.735403  2.681160  1.653386  1.483463   
113   QS-K8    15.0  2.766536  1.388401  2.683152  1.657036  1.426176   
114   QS-K9    20.0  2.574909  1.251874  2.544024  0.973064  0.984192   

     log.TLDW   log.TEL   log.BLL  ...   log.LSR  log.LLDW  log.LLIW  \
0    1.266517  0.430133  0.841587  ...  2.039216  1.279234  1.289547   
1    1.386315  0.321139  0.642719  ...  2.096122  1.263940  1.401030   
2    1.707122  0.862916  1.451607  ...  2.520469  1.096621  1.396483   
3    1.231917  0.326470  0.160756  ...  2.345546  1.270261  1.547029   
4    1.324736  0.435413  0.229040  ...  2.203945  1.384730  1.534058   
..        ...       ...       ...  ...       ...       ...       ...   
110  1.828016  0.870387  1.416913  ...  2.005686  1.439574  1.321447   
111  1.196156  0.630955  1.346705  ...  2.647061  0.498844  1.244528   
112  1.524140  0.680707  1.270692  ...  2.501802  1.837678  1.807917   
113  1.386278  0.713563  0.991068  ...  2.538133  1.436685  1.688394   
114  0.835712  0.281050  0.866269  ...  2.378856  0.333958  0.997778   

     log.MidVeinD  log.BL_PL         Tufts  Lobe.number  gene_cluster  \
0        1.743013   2.502260  3.333333e-01     6.000000             0   
1        1.733017   2.610409  1.333333e+00     5.666667             0   
2        2.186346   2.978683  1.000000e-10     8.666667             2   
3        1.820759   2.697061  1.000000e-10     6.500000             0   
4        1.939056   2.672518  1.000000e-10     6.333333             0   
..            ...        ...           ...          ...           ...   
110      1.782120   2.640152  1.000000e+00     5.000000             0   
111      2.017166   3.029277  1.666667e+00     5.666667             1   
112      2.091782   3.071046  2.000000e+00     6.000000             1   
113      2.048694   2.991316  1.333333e+00     6.333333             1   
114      1.728862   2.811029  1.666667e+00     5.000000             1   

                               gene_coordinates  \
0    [-8.431936096, -0.500913737, -11.54222572]   
1     [-8.593978553, 0.414067943, -16.68961594]   
2     [19.47262912, -1.953619719, -2.119561558]   
3     [22.37592773, -2.003944438, -2.581493893]   
4     [22.73439088, -1.946043139, -1.961701937]   
..                                          ...   
110   [-3.12037425, -0.741657104, -1.072267009]   
111  [-10.53611606, -2.040302168, -2.127410075]   
112  [-5.984694517, -0.758557842, -1.229197331]   
113    [-9.12081072, -1.974119506, 0.663090677]   
114     [-7.63567427, -2.050761891, 1.07906096]   

                                        gene_centroids  
0    [-6.734983830851852, -0.017621014611111093, -8...  
1    [-6.734983830851852, -0.017621014611111093, -8...  
2    [16.470120757953126, -1.844546040984375, 1.384...  
3    [-6.734983830851852, -0.017621014611111093, -8...  
4    [-6.734983830851852, -0.017621014611111093, -8...  
..                                                 ...  
110  [-6.734983830851852, -0.017621014611111093, -8...  
111  [-10.926670495606558, -3.6879836337213114, 5.4...  
112  [-10.926670495606558, -3.6879836337213114, 5.4...  
113  [-10.926670495606558, -3.6879836337213114, 5.4...  
114  [-10.926670495606558, -3.6879836337213114, 5.4...  

[115 rows x 22 columns]

In [1239]:
def euclidean_distance(row):
    return np.linalg.norm(np.array(row['gene_coordinates']) - np.array(row['gene_centroids']))

final_df['bkm_distance'] = final_df.apply(euclidean_distance, axis=1)

#### Control Group: KNearstNeighbors ####

In [1240]:
morph_df = pd.read_csv('data/morph.csv')
morph_df = morph_df.drop(['idx', 'Date', 'classification', 'uncertainty','Latitude', 'Longitude', 'Altitude.ft', 'Multi.Single.stem', 'General.location.Habitat', 'site', 'Putative_spp'], axis=1)
morph_df = morph_df.dropna()
morph_df = morph_df.replace(0, 1e-10)

data = morph_df.drop(['TreeNo'], axis=1)

scaler = StandardScaler()
data = scaler.fit_transform(data)
morph_df[["a", "b", "c", "d", "e"]] = data[:, [0, 11, 7, 12, 16]]

# convert to numpy matrix
morph_df['morph_coordinates'] = morph_df[['a', 'b', 'c', 'd', 'e']].values.tolist()

joined_df= morph_df.merge(gene_df, on='TreeNo')
joined_df = joined_df[['TreeNo', 'morph_coordinates', 'gene_coordinates']]

sample = joined_df.sample(sample_size)

In [1241]:
X = np.array(sample['morph_coordinates'].tolist())
y = np.array(sample['gene_coordinates'].tolist())

knn_regressor = KNeighborsRegressor(n_neighbors=3)
knn_regressor.fit(X, y)

morph_df['knn_gene_predictions'] = morph_df['morph_coordinates'].apply(lambda x: knn_regressor.predict([x])[0])
morph_df = morph_df[['TreeNo', 'knn_gene_predictions']]

final_df = morph_df.merge(final_df, on='TreeNo')

def euclidean_distance(row):
    return np.linalg.norm(np.array(row['gene_coordinates']) - np.array(row['knn_gene_predictions']))

final_df['knn_distance'] = final_df.apply(euclidean_distance, axis=1)

In [1242]:
final_df = final_df[['TreeNo', 'bkm_distance', 'knn_distance']]
final_df.to_csv('data/final_df.csv', index=False)

In [1243]:
# on average, which distance is smaller?
print(final_df['bkm_distance'].mean())
print(final_df['knn_distance'].mean())

8.924153512625013
11.134510341661226
